# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lvichi <lvichi@student.42porto.com>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/05 21:17:31 by lvichi            #+#    #+#              #
#    Updated: 2023/10/15 18:46:06 by lvichi           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CC = cc
CFLAGS = -Wall -Wextra -Werror
AR = ar rc
RM = rm -fr
FILES = *.c
OBJS = *.o

all: $(NAME) clean

$(NAME): $(OBJS)
	@$(AR) $(NAME) $(OBJS)

$(OBJS): $(FILES)
	@$(CC) $(CFLAGS) -c $(FILES)

clean:
	@$(RM) $(OBJS) 

fclean:
	@$(RM) $(OBJS) $(NAME)

re: fclean all